name = "r2-explorer"
compatibility_date = "2025-08-07"
main = "src/index.ts"
assets = { directory = "node_modules/r2-explorer/dashboard", binding = "ASSETS", html_handling = "auto-trailing-slash", not_found_handling = "single-page-application" }

# Bind R2 Buckets to your application.
# Docs: https://r2explorer.com/getting-started/add-r2-buckets/
[[r2_buckets]]
binding = "R2-Explorer"
bucket_name = "R2-Explorer"
preview_bucket_name = 'R2-Explorer'
